adverts:
  - "secret erp channel"
  - "chatroom where you say ogey rrat"
  - "ONGOING RAID (jk)"
  - "be nice!"
  - "gura in the dark room"
  - "HoloEN3 future year" # Will be replaced with current year dynamically
  - "kiara fan club"
  - "server chat yah!"
  - "fumo posting area ᗜˬᗜ"
  - "ඞ"
  - "0 days since last yab"
  - "\"\"\"appeal\"\"\" your ban ;) ;) "
  - "PIPPA NOTICE ME"
  - "yeah, me"
  - "virtual youtuber enthusiasts group"
  - "おはよううううううううう！！！"
  - "SEXXXXX"
  - "do your reps!"
  - "rigger Hate!"
  - "cum"
  - "Don't let this ERP distract you from the fact that Pekora bought a fucking MONKEEEE"
  - "I LOVE WHOOOOOOOOOOOOOOOOOOOOOOOOOORES"
  - "YOU WILL NOT PIRATE JAVS"
  - "reminder to hide your discord overlay!"

# Regular fortunes with only text and color (no side effects)
regularFortunes:
  - color: "#f51c6a"
    text: "Reply hazy, try again"
  - color: "#e7890c"
    text: "Good Luck"
  - color: "#bac200"
    text: "Average Luck"
  - color: "#43fd3b"
    text: "Good news will come to you by mail"
  - color: "#00cbb0"
    text: "ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━ !!!!"
  - color: "#2a56fb"
    text: "Better not tell you now"
  - color: "#6023f8"
    text: "Outlook good"