main: com.quakeworld.s4sfortune.Main
name: s4sfortune
version: 2.0
author: Anubis_mage
description: Roll your fortune
api-version: 1.21
commands:
    roll:
      description: Roll your fortune!
      aliases: [ fortune ]
      usage: "Usage: /roll or /fortune"
      permission: s4sfortune.roll
    funnyban:
      description: the funny ban
      aliases: [ ]
      usage: "Usage: /funnyban user reason"
      permission: s4sfortune.funnyban
    unfortunate:
      description: Removes a fortune ban from a player
      usage: "/unfortunate <player>"
      permission: s4sfortune.admin
    srolltest:
      description: used to test special rolls
      aliases: [ ]
      usage: "Usage: /srolltest <roll number>"
      permission: s4sfortune.admin
    rrolltest:
      description: used to test regular rolls
      aliases: [ ]
      usage: "Usage: /rrolltest <roll number>"
      permission: s4sfortune.admin
    checkRRolls:
      description: used to see roll index
      aliases: [ ]
      usage: "Usage: /checkRRolls"
      permission: s4sfortune.admin
    checkSRolls:
      description: used to see special roll index
      aliases: [ ]
      usage: "Usage: /checkSRolls"
      permission: s4sfortune.admin
permissions:
  s4sfortune.roll:
   description: Allows roll command
   default: true
  s4sfortune.funnyban:
   description: funny ban 
   default: op
  s4sfortune.admin:
   description: admin
   default: op
